### ISSUE TITLE
How this role could be working ?

### ISSUE THREAD

**Issue by gynarupark** [geerlingguy/ansible-role-ansible#10]
To be honest, I'm new to Ansible itself.
Does it make sense that installation of Ansible is possible by ansible-playbook ?
As I understand, installation of Ansible is prerequisite for running any playbook.
Please correct me if I have wrong information.
Thanks in advance.

**Comment by geerlingguy** [comment]
@gynarupark - Good question! This playbook is used to install Ansible on some other server.

E.g. if you're building a CI server, or a Jenkins server, or a server where you'll use `ansible-pull`, then you need to make sure Ansible is installed on _that_ server. So it's not really useful for bootstrapping itself (e.g. you can't install Ansible with Ansible unless Ansible is there), it's useful for installing Ansible where Ansible is not already present (e.g. other servers, Docker containers, Packer image builds).

**Comment by gynarupark** [comment]
Recently, I started to work with Ansible for bootstrapping in localhost.
So, I forget that Ansible can bootsrap remote hosts !!
Thanks for reminding me of it :)
