### ISSUE TITLE
Do not add repo if installing using pip

### ISSUE THREAD

**Issue by xesco** [geerlingguy/ansible-role-ansible#14]
If installation is done using pip there's no need to mess arround with apt sources.

https://github.com/geerlingguy/ansible-role-ansible/blob/00ff01ede6397cb7e009fbeadebd1458de8978ea/tasks/setup-Ubuntu.yml#L7

Thanks!

**Comment by geerlingguy** [comment]
I was going to say this could be as simple as putting all the OS install includes in a block with a condition on the `ansible_install_method`.

However, there's one feature of this role (https://github.com/geerlingguy/ansible-role-ansible/blob/00ff01ede6397cb7e009fbeadebd1458de8978ea/tasks/main.yml#L4) that relies on the package management to be working—that is, you can switch between a pip install and a system package install via the linked code above, and that would not work (if you had a package install and were switching to pip, for instance) if we made it so the package install tasks didn't run...

Kind of torn as to whether I should drop that feature or not, I would have to if I made the package install part conditional.

**Comment by xesco** [comment]
Got it! Then it make sense to keep it the way it is. 
It's kind of neat to have to option two switch from one to another, so I will keep it that way.

Feel free to close the issue :)

Thanks.

**Comment by geerlingguy** [comment]
Sounds good, thanks for posting the issue, it's definitely something where there are a few benefits either way.
