### ISSUE TITLE
Ubuntu 20.04 Focal Fossa not yet supported by Ansible's PPA

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-ansible#18]
I was updating tests to work with 20.04, but it seems that it's not yet supported by Ansible's official PPA: https://github.com/ansible/ansible/pull/69161

Tracking here; for now, people on Ubuntu 20.04 using this role should just use the pip install method instead of package.

**Comment by bayeslearner** [comment]
Still doesn't work.  But the ansible version included with ubuntu is the latest stable version.  Maybe use that in playbook?

**Comment by geerlingguy** [comment]
I typically use pip for installs at this point, because packaged installs are going to probably get weirder with the new stuff happening in Ansible 2.10+.

**Comment by tomkivlin** [comment]
Just noting that I used this role on Ubuntu 20.04 today and it worked fine. Also noticed the referenced ansible/ansible PR has been merged.

**Comment by geerlingguy** [comment]
@tomkivlin - Thanks for posting, looks like it's passing in CI too! Yay :)
