### ISSUE TITLE
Ansible Galaxy installation issue

### ISSUE THREAD

**Issue by aosmialowski** [geerlingguy/ansible-role-ansible#2]
Hi,

unfortunately, this role is not installable via Ansible Galaxy due to strange error: https://galaxy.ansible.com/list#/roles/1007. As you can see there's some weird issue with role name under `Installation` section: `$ ansible-galaxy install geerlingguy. `.

The output of the installation process via `ansible-galaxy`:
```
andrzej@PC:~/workspace$ ansible-galaxy install -r requirements.yml
- downloading role 'ansible', owned by geerlingguy
- sorry, geerlingguy.ansible was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.
```

**Comment by geerlingguy** [comment]
See: https://github.com/ansible/ansible/issues/11556 :(

**Comment by aosmialowski** [comment]
Wow, that sucks :( Anyway, we can src the role from its Github repo.
